replicaCount: 1
restartPolicy: Never

index: >-
  <h1>Hello</h1>
  <p>You got it dude!</p>

image:
  repository: nginx
  tag: 1.14.0
  pullPolicy: IfNotPresent

service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: NodePort
  port: 80
  nodePort: "30001"

podAnnotations: {}

resources: {}

nodeSelector: {}
